#!/usr/bin/env python3
"""Discover, register, build, and run local PintOS debug tests."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class DebugTest:
    source: Path
    rel: Path
    name: str
    function: str


def sanitize(value: str, sep: str) -> str:
    value = re.sub(r"[^A-Za-z0-9]+", sep, value)
    value = re.sub(rf"{re.escape(sep)}+", sep, value)
    return value.strip(sep).lower()


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def strip_c_comments(content: str) -> str:
    return re.sub(r"/\*.*?\*/|//[^\n]*", "", content, flags=re.DOTALL)


def discover(tests_dir: Path) -> list[DebugTest]:
    tests: list[DebugTest] = []
    for source in sorted(tests_dir.rglob("*.c")):
        rel = source.relative_to(tests_dir)
        stem = rel.with_suffix("").as_posix()
        name_suffix = sanitize(stem, "-")
        fn_suffix = sanitize(stem, "_")
        if not name_suffix or not fn_suffix:
            continue
        if fn_suffix[0].isdigit():
            fn_suffix = "_" + fn_suffix
        tests.append(
            DebugTest(
                source=source,
                rel=rel,
                name=f"debug-{name_suffix}",
                function=f"debug_test_{fn_suffix}",
            )
        )
    return tests


def validate_sources(tests: list[DebugTest]) -> None:
    pattern = re.compile(r"\bDEBUG_TEST\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)")
    errors: list[str] = []
    for test in tests:
        try:
            content = test.source.read_text(encoding="utf-8")
        except OSError as exc:
            errors.append(f"{test.rel}: cannot read source: {exc}")
            continue

        matches = pattern.findall(strip_c_comments(content))
        expected = test.function.removeprefix("debug_test_")
        if expected not in matches:
            found = ", ".join(matches) if matches else "none"
            errors.append(
                f"{test.rel}: expected DEBUG_TEST ({expected}), "
                f"but found {found}"
            )
        if len(matches) != 1:
            errors.append(
                f"{test.rel}: expected exactly one DEBUG_TEST macro, "
                f"but found {len(matches)}"
            )

    if errors:
        fail("invalid debug test source:\n" + "\n".join(f"  {error}" for error in errors))


def ensure_unique(tests: list[DebugTest]) -> None:
    by_name: dict[str, Path] = {}
    by_function: dict[str, Path] = {}
    for test in tests:
        if test.name in by_name:
            fail(f"duplicate debug test name {test.name}: {by_name[test.name]} and {test.rel}")
        if test.function in by_function:
            fail(
                f"duplicate debug test function {test.function}: "
                f"{by_function[test.function]} and {test.rel}"
            )
        by_name[test.name] = test.rel
        by_function[test.function] = test.rel


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def generate(tool_dir: Path, tests: list[DebugTest]) -> bool:
    generated = tool_dir / "generated"
    header_lines = [
        "/* Generated by pintos/tools/debug-test/run-debug-tests.py. */",
        "#ifndef DEBUG_TEST_TOOL_GENERATED_DEBUG_TESTS_H",
        "#define DEBUG_TEST_TOOL_GENERATED_DEBUG_TESTS_H",
        "",
    ]
    for test in tests:
        header_lines.append(f"extern test_func {test.function};")
    header_lines.extend(["", "#endif /* tools/debug-test/generated/debug-tests.h */", ""])

    inc_lines = ["/* Generated by pintos/tools/debug-test/run-debug-tests.py. */"]
    for test in tests:
        inc_lines.append(f'    {{"{test.name}", {test.function}}},')
    inc_lines.append("")

    mk_lines = ["# Generated by pintos/tools/debug-test/run-debug-tests.py."]
    if tests:
        mk_lines.append("tests/threads_SRC += \\")
        for idx, test in enumerate(tests):
            suffix = " \\" if idx != len(tests) - 1 else ""
            mk_lines.append(f"\tdebug/{test.rel.as_posix()}{suffix}")
    mk_lines.append("")

    list_lines = [f"{test.name}\tdebug/{test.rel.as_posix()}" for test in tests]
    list_lines.append("")

    changed = False
    changed |= write_if_changed(generated / "debug-tests.h", "\n".join(header_lines))
    changed |= write_if_changed(generated / "debug-tests.inc", "\n".join(inc_lines))
    changed |= write_if_changed(generated / "debug-tests.mk", "\n".join(mk_lines))
    changed |= write_if_changed(generated / "debug-tests.list", "\n".join(list_lines))
    return changed


def make_build_dirs(build_dir: Path, tests: list[DebugTest]) -> None:
    for test in tests:
        obj_dir = build_dir / "debug" / test.rel.parent
        obj_dir.mkdir(parents=True, exist_ok=True)
    (build_dir / "debug-test-results").mkdir(parents=True, exist_ok=True)


def resolve_tests(tests: list[DebugTest], requested: str | None) -> list[DebugTest]:
    if not requested:
        return tests

    wanted = requested.strip()
    aliases: dict[str, list[DebugTest]] = {}

    def add_alias(alias: str, test: DebugTest) -> None:
        aliases.setdefault(alias, []).append(test)

    for test in tests:
        rel = test.rel.as_posix()
        rel_no_ext = test.rel.with_suffix("").as_posix()
        stem = test.rel.stem
        name_suffix = test.name.removeprefix("debug-")

        add_alias(test.name, test)
        add_alias(name_suffix, test)
        add_alias(rel, test)
        add_alias(rel_no_ext, test)
        add_alias(test.rel.name, test)
        add_alias(stem, test)
        add_alias(f"debug/{rel}", test)
        add_alias(f"debug/{rel_no_ext}", test)

    if wanted not in aliases:
        available = "\n".join(
            f"  {test.rel.stem} | {test.rel.with_suffix('').as_posix()} | {test.name}"
            for test in tests
        )
        fail(f"unknown debug test {wanted!r}\nAvailable tests:\n{available}")

    matched = aliases[wanted]
    unique = {test.name: test for test in matched}
    if len(unique) > 1:
        matches = "\n".join(
            f"  {test.rel.with_suffix('').as_posix()} -> {test.name}"
            for test in unique.values()
        )
        fail(f"ambiguous debug test {wanted!r}. Use a longer name:\n{matches}")
    return [next(iter(unique.values()))]


def run(cmd: list[str], cwd: Path, **kwargs) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=str(cwd), text=True, **kwargs)


def remove_stale_debug_test_deps(build_dir: Path) -> None:
    stale_markers = (
        "tools/debug-test/generated/",
        "debug/",
    )
    for dep in build_dir.rglob("*.d"):
        try:
            content = dep.read_text(encoding="utf-8")
        except OSError:
            continue
        if any(marker in content for marker in stale_markers):
            dep.unlink()


def remove_registry_objects(build_dir: Path) -> None:
    for rel in (
        "tests/threads/tests.o",
        "tests/threads/tests.d",
        "kernel.o",
        "kernel.bin",
        "os.dsk",
    ):
        path = build_dir / rel
        try:
            path.unlink()
        except FileNotFoundError:
            pass


def build_kernel(build_dir: Path, registry_changed: bool) -> None:
    run(["make", "Makefile"], cwd=build_dir, check=True)
    remove_stale_debug_test_deps(build_dir)
    if registry_changed:
        remove_registry_objects(build_dir)
    run(["make"], cwd=build_dir, check=True)


def pintos_cmd(args: argparse.Namespace, test: DebugTest) -> list[str]:
    cmd = [
        "../../utils/pintos",
        "-v",
        "-k",
        "-m",
        str(args.memory),
        f"--fs-disk={args.fs_disk}",
        f"--swap-disk={args.swap_disk}",
    ]
    if args.debug:
        cmd.append("--gdb")
    else:
        cmd.extend(["-T", str(args.timeout)])
    cmd.extend(["--", "-q", "-f", "-threads-tests", "run", test.name])
    return cmd


def is_gdb_port_listening(port: int = 1234) -> bool:
    port_hex = f"{port:04X}"
    for proc_path in (Path("/proc/net/tcp"), Path("/proc/net/tcp6")):
        try:
            lines = proc_path.read_text(encoding="ascii").splitlines()[1:]
        except OSError:
            continue

        for line in lines:
            fields = line.split()
            if len(fields) < 4:
                continue
            local_address = fields[1]
            state = fields[3]
            _, local_port = local_address.rsplit(":", 1)
            if local_port.upper() == port_hex and state == "0A":
                return True
    return False


def wait_for_gdb_port(process: subprocess.Popen[str], timeout: float = 10.0) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if process.poll() is not None:
            return False
        if is_gdb_port_listening():
            return True
        time.sleep(0.1)
    return False


def gdb_cmd(args: argparse.Namespace, build_dir: Path, test: DebugTest) -> list[str]:
    gdb_script = args.project_root.resolve() / ".vscode" / "pintos-debug.gdb"
    breakpoints = args.breakpoint or [test.function]
    cmd = ["gdb", "-q", "kernel.o"]
    if gdb_script.exists():
        cmd.extend(["-ex", f"source {gdb_script}"])
    cmd.extend(["-ex", "target remote localhost:1234"])
    for breakpoint in breakpoints:
        cmd.extend(["-ex", f"break {breakpoint}"])
    cmd.extend(["-ex", "continue"])
    return cmd


def stop_process(process: subprocess.Popen[str]) -> None:
    if process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=2)
    except subprocess.TimeoutExpired:
        process.kill()


def run_one(build_dir: Path, args: argparse.Namespace, test: DebugTest) -> bool:
    if args.debug:
        print(f"[debug-start] {test.name}: starting QEMU GDB server", flush=True)
        process = subprocess.Popen(pintos_cmd(args, test), cwd=str(build_dir), text=True)
        if not wait_for_gdb_port(process):
            print(f"[debug-fail] {test.name}: GDB server did not open localhost:1234", file=sys.stderr)
            stop_process(process)
            return False
        print(f"[debug-ready] {test.name}: GDB server listening on localhost:1234", flush=True)
        if args.debug_mode == "wait":
            print("              VSCode can attach now, or run: gdb -q kernel.o -ex 'target remote localhost:1234'", flush=True)
            try:
                return process.wait() == 0
            except KeyboardInterrupt:
                stop_process(process)
                return False

        print(f"[gdb-start] breaking at {', '.join(args.breakpoint or [test.function])}", flush=True)
        try:
            gdb_result = run(gdb_cmd(args, build_dir, test), cwd=build_dir)
            return gdb_result.returncode == 0
        except KeyboardInterrupt:
            return False
        finally:
            stop_process(process)

    result = run(
        pintos_cmd(args, test),
        cwd=build_dir,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    out_path = build_dir / "debug-test-results" / f"{test.name}.output"
    err_path = build_dir / "debug-test-results" / f"{test.name}.errors"
    out_path.write_text(result.stdout, encoding="utf-8")
    err_path.write_text(result.stderr, encoding="utf-8")

    passed = (
        result.returncode == 0
        and f"({test.name}) PASS" in result.stdout
        and "PANIC" not in result.stdout
        and "TIMEOUT" not in result.stdout
    )
    status = "pass" if passed else "FAIL"
    print(f"{status} {test.name}")
    if not passed:
        print(f"  output: {out_path}")
        print(f"  errors: {err_path}")
    return passed


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=Path.cwd())
    parser.add_argument("--build", default="vm", choices=["threads", "userprog", "vm", "filesys"])
    parser.add_argument("--test")
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--debug-mode", choices=["gdb", "wait"], default="gdb")
    parser.add_argument("--breakpoint", action="append")
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--timeout", type=int, default=60)
    parser.add_argument("--memory", type=int, default=20)
    parser.add_argument("--swap-disk", default="4")
    parser.add_argument("--fs-disk", default="2")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.project_root.resolve()
    pintos_dir = root / "pintos"
    tool_dir = pintos_dir / "tools" / "debug-test"
    tests_dir = pintos_dir / "debug"
    build_dir = pintos_dir / args.build / "build"

    tests = discover(tests_dir)
    ensure_unique(tests)

    if args.list:
        for test in tests:
            print(f"{test.name}\tdebug/{test.rel}")
        return 0

    selected = resolve_tests(tests, args.test)
    if not selected:
        print("No debug tests found under pintos/debug.")
        return 0
    if args.debug and len(selected) != 1:
        fail("debug mode needs exactly one test. Use TEST=<name>.")

    validate_sources(selected)
    registry_changed = generate(tool_dir, selected)

    make_build_dirs(build_dir, selected)
    build_kernel(build_dir, registry_changed)

    failures = 0
    for test in selected:
        if not run_one(build_dir, args, test):
            failures += 1
            if args.debug:
                break

    if failures:
        print(f"{failures} of {len(selected)} debug tests failed.")
        return 1
    print(f"All {len(selected)} debug tests passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
